name: 'No Circular Deps Action'
description: 'Console Hello World!'
author: 'Sanyam Aggarwal'

inputs:
  baseFilePath:
    description: 'file path containing .json file to skip dependencies'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Detect Circular Dependencies
      id: nocirculardeps
      run: node action.js
      shell: bash

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isCircularDependencyPresent == 'true' }}
      with:
        message: |
          :round_pushpin: Branch circular dependencies :infinity:. Details in next comment

    - name: Comment PR with branch circular deps file
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isCircularDependencyPresent == 'true' }}
      with:
        filePath: ${{ steps.nocirculardeps.outputs.branchCircularDepsFilePath }}

    - name: Comment PR with reduced circular deps
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isCircularDependencyCountReduced == 'true' && steps.nocirculardeps.outputs.isNewCircularDependencyIntroduced == 'false' }}
      message: |
          :round_pushpin: This PR reduces circular dependencies :infinity:. Make sure to update them in skipFile.

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isNewCircularDependencyIntroduced == 'true' }}
      with:
        message: |
          :round_pushpin: Detected new circular dependencies :infinity:. Details in next comment

    - name: Comment PR with new circular deps file
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isNewCircularDependencyIntroduced == 'true' }}
      with:
        filePath: ${{ steps.nocirculardeps.outputs.newCircularDepsFilePath }}
    

branding:
  icon: 'repeat'
  color: 'red'