name: 'No Circular Deps Action'
description: 'Detect & Validate Circular Dependencies'
author: 'Sanyam Aggarwal'

inputs:
  baseFilePath:
    description: 'file path containing .json file to skip dependencies'
    required: false
    default: "$GITHUB_WORKSPACE"

runs:
  using: 'composite'
  steps:
    - name: ⬇️ Checkout Repository
      uses: actions/checkout@v3
      with:
        path: action-no-circular-deps
        

    # - name: 📥 npm install
    #   uses: bahmutov/npm-install@v1.8.5

    - name: npm install
      run: |
        npm ci
      shell: bash

    - name: Detect Circular Dependencies
      id: nocirculardeps
      run: node "${{ github.action_path }}/action.js"
      shell: bash

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isCircularDependencyPresent == 'true' }}
      with:
        message: |
          :round_pushpin: Branch circular dependencies :infinity:. Details in next comment

    - name: Comment PR with branch circular deps file
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isCircularDependencyPresent == 'true' }}
      with:
        filePath: ${{ steps.nocirculardeps.outputs.branchCircularDepsFilePath }}

    - name: Comment PR with reduced circular deps
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isCircularDependencyCountReduced == 'true' && steps.nocirculardeps.outputs.isNewCircularDependencyIntroduced == 'false' }}
      with:
        message: |
          :round_pushpin: This PR reduces circular dependencies :infinity:. Make sure to update them in skipFile.

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isNewCircularDependencyIntroduced == 'true' }}
      with:
        message: |
          :round_pushpin: Detected new circular dependencies :infinity:. Details in next comment

    - name: Comment PR with new circular deps file
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ steps.nocirculardeps.outputs.isNewCircularDependencyIntroduced == 'true' }}
      with:
        filePath: ${{ steps.nocirculardeps.outputs.newCircularDepsFilePath }}
    

branding:
  icon: 'repeat'
  color: 'red'