name: 'No Circular Deps Action'
description: 'Detect & Validate Circular Dependencies'
author: 'Sanyam Aggarwal'

branding:
  icon: 'repeat'
  color: 'red'

inputs:
  baseFilePath:
    description: 'file path containing .json file to skip dependencies'
    required: false
    default: ''

runs:
  using: 'node12'
  main: action.js